### ISSUE TITLE
bug: Deltas Fail PRs when File is Deleted

### ISSUE THREAD

**Issue by therynamo** [anuraag016/Jest-Coverage-Diff#29]
We've observed on a few occasions that `deleted` files are causing `delta`s to fail CI. 

```
❌ | App/My/File.tsx | 89.47 | 69.23 | 100 | 89.47
-- | -- | -- | -- | -- | --
```

It isn't entirely clear if this is the reason - but it seems likely that the diff between `main` and `branch` is marking deleted coverage as a reduced delta. 

This may potentially come down to philosophy/semantics. I think technically the term `delta` would apply correctly here in that it is a net change in reduced coverage. However, I think for the purposes of this plugin the `delta` metric should be utilized to determine if there is "lost" coverage on "existing files". 

I'd be curious to hear thoughts on this one too. I may not being viewing it through the correct lens. 

Thanks in advance!

**Comment by anuraag016** [comment]
I enjoy the overall engagement and a chance to improve code, finding time for the same does get a bit difficult at times though. 
I am happy to take contributions, feel free to raise a PR for any feature/bug/proposal 😄

**Comment by therynamo** [comment]
Hey @anuraag016 - just checking to see if you've had a chance to test this out yet?

**Comment by anuraag016** [comment]
Hey @therynamo, 
Apologies for the delay, I was on a vacation recently and have been swamped with other work since I have been back, haven't been able to test it yet. I am planning to look into it and complete this in the upcoming weekend.

**Comment by therynamo** [comment]
No worries @anuraag016 - life comes first 😄 !

**Comment by anuraag016** [comment]
@therynamo completed the PR after testing and created a new Release V1.4. Have added SHA to comment as requested, felt that it makes sense as we are now giving an option to update the same comment. Do test it out 😄

**Comment by therynamo** [comment]
Awesome! Thanks so much for the changes you've made! I'll test them out this week!
